# Generated by Django 4.1.7 on 2023-03-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        migrations.CreateModel(
            name='Patients_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursady', 'Thusday'), ('friday', 'Friday')], max_length=50, null=True)),
                ('num_patients', models.PositiveIntegerField()),
                ('treated_patients', models.PositiveIntegerField()),
                ('num_outpatients', models.PositiveIntegerField(default=0)),
                ('num_inpatients', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('general_health', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('water_balance', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.DeleteModel(
            name='Patient_health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=70, null=True)),
                ('january', models.IntegerField(default=0)),
                ('February', models.IntegerField(default=0)),
                ('March', models.IntegerField(default=0)),
                ('April', models.IntegerField(default=0)),
                ('May', models.IntegerField(default=0)),
                ('Jume', models.IntegerField(default=0)),
                ('July', models.IntegerField(default=0)),
                ('August', models.IntegerField(default=0)),
                ('September', models.IntegerField(default=0)),
                ('October', models.IntegerField(default=0)),
                ('November', models.IntegerField(default=0)),
                ('December', models.IntegerField(default=0)),
            ],
        ),
    ]
